### ISSUE TITLE
Error 401 on TL-SG108E 3.0

### ISSUE THREAD

**Issue by jeffersonraimon** [guillerg86/zabbix-template-sg108e#1]
Congrats for this repo

I have a TL-SG108E version 3.0 and when I try test, I received the error 401.
IP, username and password is Ok

Can you help?

Traceback (most recent call last):
  File "/home/raimonxd/zabbix-template-sg108e/tplinkswitch2zabbix.py", line 179, in <module>
    session = dao.do_login()
  File "/home/raimonxd/zabbix-template-sg108e/tplinkswitch2zabbix.py", line 76, in do_login
    raise Exception(f"Error: HTTP Status code: {str(resp.status_code)}")
Exception: Error: HTTP Status code: 401

**Comment by jeffersonraimon** [comment]
Firmware version: 1.0.0 Build 20171214 Rel.70905

**Comment by guillerg86** [comment]
Hi @jeffersonraimon , could you send me the request and response for login process, visit status port page and statistics port page.

You could get the Request and Response using Burpsuite tool (capturing the messages).

I don't have version 3 of this switch but I think with that info, I can try to parse

**Comment by jeffersonraimon** [comment]
@guillerg86 Thanks man. 
I saved the HTTP history items in this file zipped and i can open with https://adityatelange.github.io/bhhb/


[sw_tplink.zip](https://github.com/guillerg86/zabbix-template-sg108e/files/14470450/sw_tplink.zip)

**Comment by guillerg86** [comment]
Seems that this model, the response of login is HTTP 401 but it works. Just checked the other pages, and seems that have same structure... so fast fix you could try is

Line 72: 

```
if resp.status_code == 200:
```
change for

```
if resp.status_code in [200,401]:
```

Try again and tell if works

**Comment by jeffersonraimon** [comment]
Works, thanks!

![image](https://github.com/guillerg86/zabbix-template-sg108e/assets/80064475/10e75789-6f90-415e-9aed-5bf0fc7f7994)

**Comment by guillerg86** [comment]
Fix merged, thanks for testing

And remember change admin password ;)

**Comment by guillerg86** [comment]
Fix merged, thanks for testing

And remember change admin password ;)
